DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE HOME CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE USER CASCADE CONSTRAINTS;


CREATE TABLE USER (
  USER_EMAIL VARCHAR2(25) NOT NULL,
  USER_NAME VARCHAR2(50) NOT NULL,
  USER_SURNAME VARCHAR2(20) NOT NULL,
  USER_PASSWORD VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_USER PRIMARY KEY (USER_EMAIL)
);

CREATE TABLE ADMIN (
  ADMIN_EMAIL VARCHAR2(25) NOT NULL,
  CONSTRAINT PK_ADMIN PRIMARY KEY (ADMIN_EMAIL)
);

CREATE TABLE HOME (
  HOME_NAME VARCHAR2(30) NOT NULL,
  HOME_EMAIL VARCHAR2(25) NOT NULL,
  HOME_CITY VARCHAR2(25) NOT NULL,
  HOME_DESCRIPTION_FULL VARCHAR2(200) NOT NULL,
  HOME_DESCRIPTION_SHORT VARCHAR2(50) NOT NULL,
  HOME_TYPE VARCHAR2(3) NOT NULL,
  HOME_GUESTS NUMBER(3) NOT NULL,
  HOME_PHOTOS VARCHAR(45),
  HOME_PRICE_NIGHT DECIMAL(3,2) NOT NULL,
  HOME_AV_DATE_INIT DATE NOT NULL,
  HOME_AV_DATE_FIN DATE NOT NULL,
  CONSTRAINT PK_HOME PRIMARY KEY (HOME_NAME, HOME_EMAIL),
  CONSTRAINT FK_HOME FOREIGN KEY (HOME_EMAIL) REFERENCES USER ON DELETE CASCADE
);

CREATE TABLE BOOKING (
  BOOKING_EMAIL_USER VARCHAR(25) NOT NULL,
  BOOKING_NAME_HOME VARCHAR(30) NOT NULL,
  BOOKING_EMAIL_HOME VARCHAR(25) NOT NULL,
  BOOKING_DATE_IN DATE NOT NULL,
  BOOKING_DATE_OUT DATE NOT NULL,
  BOOKING_CARD_NUM VARCHAR2(20) NOT NULL,
  BOOKING_EXP_CODE VARCHAR2(6) NOT NULL,
  BOOKING_CONFIRMED BOOLEAN NOT NULL,
  CONSTRAINT PK_BOOKING PRIMARY KEY (BOOKING_EMAIL_USER, BOOKING_NAME_HOME, BOOKING_EMAIL_HOME),
  CONSTRAINT FK_BOOKING1 FOREIGN KEY (BOOKING_EMAIL_USER) REFERENCES USER ON DELETE CASCADE,
  CONSTRAINT FK_BOOKING2 FOREIGN KEY (BOOKING_NAME_HOME, BOOKING_EMAIL_HOME) REFERENCES HOME ON DELETE CASCADE
);
