CREATE DATABASE IF NOT EXISTS `tiwbnb`;
USE `tiwbnb`;

DROP TABLE IF EXISTS BOOKING CASCADE;
DROP TABLE IF EXISTS HOME CASCADE;
DROP TABLE IF EXISTS ADMIN CASCADE;
DROP TABLE IF EXISTS USER CASCADE;


CREATE TABLE USER (
  USER_ID INT NOT NULL,
  USER_EMAIL VARCHAR(25) NOT NULL,
  USER_NAME VARCHAR(50) NOT NULL,
  USER_SURNAME VARCHAR(20) NOT NULL,
  USER_PASSWORD VARCHAR(20) NOT NULL,
  CONSTRAINT PK_USER PRIMARY KEY (USER_ID),
  CONSTRAINT UNIQUE_USER UNIQUE (USER_EMAIL)
);

CREATE TABLE ADMIN (
  ADMIN_ID INT NOT NULL,
  ADMIN_EMAIL VARCHAR(25) NOT NULL,
  CONSTRAINT PK_ADMIN PRIMARY KEY (ADMIN_ID),
  CONSTRAINT UNIQUE_ADMIN UNIQUE (ADMIN_EMAIL)
);

CREATE TABLE HOME (
  HOME_ID INT NOT NULL,
  HOME_NAME VARCHAR(30) NOT NULL,
  HOME_EMAIL VARCHAR(25) NOT NULL,
  HOME_CITY VARCHAR(25) NOT NULL,
  HOME_DESCRIPTION_FULL VARCHAR(200) NOT NULL,
  HOME_DESCRIPTION_SHORT VARCHAR(50) NOT NULL,
  HOME_TYPE VARCHAR(3) NOT NULL,
  HOME_GUESTS INT(3) NOT NULL,
  HOME_PHOTOS VARCHAR(45),
  HOME_PRICE_NIGHT DECIMAL(6,2) NOT NULL,
  HOME_AV_DATE_INIT DATE NOT NULL,
  HOME_AV_DATE_FIN DATE NOT NULL,
  CONSTRAINT PK_HOME PRIMARY KEY (HOME_ID),
  CONSTRAINT UNIQUE_HOME UNIQUE (HOME_NAME, HOME_EMAIL),
  CONSTRAINT FK_HOME FOREIGN KEY (HOME_EMAIL) REFERENCES USER (USER_EMAIL) ON DELETE CASCADE
);

CREATE TABLE BOOKING (
  BOOKING_ID INT NOT NULL,
  BOOKING_EMAIL_USER VARCHAR(25) NOT NULL,
  BOOKING_NAME_HOME VARCHAR(30) NOT NULL,
  BOOKING_EMAIL_HOME VARCHAR(25) NOT NULL,
  BOOKING_DATE_IN DATE NOT NULL,
  BOOKING_DATE_OUT DATE NOT NULL,
  BOOKING_CARD_NUM INT(16) NOT NULL,
  BOOKING_EXP_CODE VARCHAR(6) NOT NULL,
  BOOKING_CV2 INT(3) NOT NULL,
  BOOKING_CONFIRMED BOOLEAN NOT NULL,
  CONSTRAINT PK_BOOKING PRIMARY KEY (BOOKING_ID),
  CONSTRAINT UNIQUE_BOOKING UNIQUE (BOOKING_EMAIL_USER, BOOKING_NAME_HOME, BOOKING_EMAIL_HOME),
  CONSTRAINT FK_BOOKING1 FOREIGN KEY (BOOKING_EMAIL_USER) REFERENCES USER (USER_EMAIL) ON DELETE CASCADE,
  CONSTRAINT FK_BOOKING2 FOREIGN KEY (BOOKING_NAME_HOME, BOOKING_EMAIL_HOME) REFERENCES HOME (HOME_NAME, HOME_EMAIL) ON DELETE CASCADE
);

INSERT INTO `USER` VALUES (1, 'mail@ibm.com', 'Fernando', 'Garcia', 'secret');
INSERT INTO `USER` VALUES (2, 'mail@redsys.es', 'Fernando', 'Piqueras', 'password');
INSERT INTO `USER` VALUES (3, 'toni@ibm.com', 'Toni', 'Surname', 'tony');
INSERT INTO `USER` VALUES (4, 'guille@ibm.com', 'Guille', 'Surname', 'guille');
INSERT INTO `USER` VALUES (5, 'example@ibm.com', 'dummy', 'Insert', 'secret');
INSERT INTO `USER` VALUES (6, 'example@amazon.com', 'user', 'Surname', 'user');

INSERT INTO `ADMIN` VALUE (1, 'sysadmin');
INSERT INTO `ADMIN` VALUE (2, 'ibm');
INSERT INTO `ADMIN` VALUE (3, 'tzarraon@inf.uc3m.es');

INSERT INTO `HOME` VALUE (1, 'Loft', 'mail@ibm.com', 'Madrid', 'Full Description', 'Short Description', 
'apt', 5, 'path/image/loft', 420, '20180101', '20181231');
INSERT INTO `HOME` VALUE (2, 'Condo', 'mail@ibm.com', 'NY', 'Full Description', 'Short Description', 
'pri', 1, 'path/image/condo', 70, '20180101', '20181231');
INSERT INTO `HOME` VALUE (3, 'Suite', 'mail@redsys.es', 'Madrid', 'Full Description', 'Short Description', 
'apt', 3, 'path/image/suite', 1337.70, '20180101', '20181231');
