CREATE DATABASE IF NOT EXISTS `tiwbnb`;
USE `tiwbnb`;

DROP TABLE IF EXISTS BOOKING CASCADE;
DROP TABLE IF EXISTS HOME CASCADE;
DROP TABLE IF EXISTS ADMIN CASCADE;
DROP TABLE IF EXISTS USER CASCADE;


CREATE TABLE USER (
  USER_ID INT NOT NULL,
  USER_EMAIL VARCHAR(25) NOT NULL,
  USER_NAME VARCHAR(50) NOT NULL,
  USER_SURNAME VARCHAR(20) NOT NULL,
  USER_PASSWORD VARCHAR(20) NOT NULL,
  CONSTRAINT PK_USER PRIMARY KEY (USER_ID),
  CONSTRAINT UNIQUE_USER PRIMARY KEY (USER_EMAIL)
);

CREATE TABLE ADMIN (
  ADMIN_ID INT NOT NULL,
  ADMIN_EMAIL VARCHAR(25) NOT NULL,
  CONSTRAINT PK_ADMIN PRIMARY KEY (ADMIN_ID),
  CONSTRAINT UNIQUE_ADMIN PRIMARY KEY (ADMIN_EMAIL)
);

CREATE TABLE HOME (
  HOME_ID INT NOT NULL,
  HOME_NAME VARCHAR(30) NOT NULL,
  HOME_EMAIL VARCHAR(25) NOT NULL,
  HOME_CITY VARCHAR(25) NOT NULL,
  HOME_DESCRIPTION_FULL VARCHAR(200) NOT NULL,
  HOME_DESCRIPTION_SHORT VARCHAR(50) NOT NULL,
  HOME_TYPE VARCHAR(3) NOT NULL,
  HOME_GUESTS INT(3) NOT NULL,
  HOME_PHOTOS VARCHAR(45),
  HOME_PRICE_NIGHT DECIMAL(3,2) NOT NULL,
  HOME_AV_DATE_INIT DATE NOT NULL,
  HOME_AV_DATE_FIN DATE NOT NULL,
  CONSTRAINT PK_HOME PRIMARY KEY (HOME_ID),
  CONSTRAINT UNIQUE_HOME PRIMARY KEY (HOME_NAME, HOME_EMAIL),
  CONSTRAINT FK_HOME FOREIGN KEY (HOME_EMAIL) REFERENCES USER (USER_EMAIL) ON DELETE CASCADE
);

CREATE TABLE BOOKING (
  BOOKING_ID INT NOT NULL,
  BOOKING_EMAIL_USER VARCHAR(25) NOT NULL,
  BOOKING_NAME_HOME VARCHAR(30) NOT NULL,
  BOOKING_EMAIL_HOME VARCHAR(25) NOT NULL,
  BOOKING_DATE_IN DATE NOT NULL,
  BOOKING_DATE_OUT DATE NOT NULL,
  BOOKING_CARD_NUM INT(16) NOT NULL,
  BOOKING_EXP_CODE VARCHAR(6) NOT NULL,
  BOOKING_CV2 INT(3) NOT NULL,
  BOOKING_CONFIRMED BOOLEAN NOT NULL,
  CONSTRAINT PK_BOOKING PRIMARY KEY (BOOKING_ID),
  CONSTRAINT UNIQUE_BOOKING PRIMARY KEY (BOOKING_EMAIL_USER, BOOKING_NAME_HOME, BOOKING_EMAIL_HOME),
  CONSTRAINT FK_BOOKING1 FOREIGN KEY (BOOKING_EMAIL_USER) REFERENCES USER (USER_EMAIL) ON DELETE CASCADE,
  CONSTRAINT FK_BOOKING2 FOREIGN KEY (BOOKING_NAME_HOME, BOOKING_EMAIL_HOME) REFERENCES HOME (HOME_NAME, HOME_EMAIL) ON DELETE CASCADE
);